language: r
sudo: required

r: 
  - oldrel
  - release
  - devel
  
os:
  - linux
  - osx

after_failure:
- "./travis-tool.sh dump_logs"

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  slack:
    secure: P8tSHsBe+PED/MMKquThYzomcilKz//aY/58vgAWR3DAz66DDov8w++Fmj1SPLnXO67PtMBwG3crqaKlN1X6TT3ADE0E55a2Ml5xSzbGpSTF5GTxS5XhbFZ/BBesQJU8288yCjo4lcAJqz3A96HxdP28X4/4d5p3SamW0vQ7Q/Q=
